// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEE8Kf5fa_2Aebo-8Zw7erfFbU_7lleJo',
    appId: '1:829449279254:web:8db0e9e3aa3a42cbe7a237',
    messagingSenderId: '829449279254',
    projectId: 'nutricare-de0bf',
    authDomain: 'nutricare-de0bf.firebaseapp.com',
    storageBucket: 'nutricare-de0bf.firebasestorage.app',
    measurementId: 'G-QCTTSLCB8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-EzGMUA8_33IumNgiNnDf_so7byBfIRY',
    appId: '1:829449279254:android:6ef30caf126e2112e7a237',
    messagingSenderId: '829449279254',
    projectId: 'nutricare-de0bf',
    storageBucket: 'nutricare-de0bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-qgp19EN1KRo81JQnhriw5t5a3VQCUA',
    appId: '1:829449279254:ios:805f603b79a7f4abe7a237',
    messagingSenderId: '829449279254',
    projectId: 'nutricare-de0bf',
    storageBucket: 'nutricare-de0bf.firebasestorage.app',
    iosBundleId: 'com.nutricare.nutricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-qgp19EN1KRo81JQnhriw5t5a3VQCUA',
    appId: '1:829449279254:ios:805f603b79a7f4abe7a237',
    messagingSenderId: '829449279254',
    projectId: 'nutricare-de0bf',
    storageBucket: 'nutricare-de0bf.firebasestorage.app',
    iosBundleId: 'com.nutricare.nutricare',
  );
}
